smsCore/Controllers/LibraryController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models;
using smsCore.Data.Helpers;
using Syncfusion.EJ2.Base;

namespace smsCore.Controllers
{
   
    public class LibraryController : BaseController
    {
        // GET: Library
        private readonly SchoolEntities db;
        
        public LibraryController(SchoolEntities db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string Create(Library library)
        {
            try
            {                
                db.Libraries.Add(library);
                db.SaveChanges();
                return "success";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        // Edit: Library
        public IActionResult EditLibrary(int id)
        {
            var editLib = db.Libraries.Where(n => n.ID == id).FirstOrDefault();
            return View(editLib);
        }

        [HttpPost]
        public string EditLibrary(Library library)
        {
            var editLib = db.Libraries.Find(library.ID);
            if (editLib != null)
            {
                editLib.LibraryName = library.LibraryName;
                editLib.Code = library.Code;
                editLib.OpeningTime = library.OpeningTime;
                editLib.ClosingTime = library.ClosingTime;
                db.SaveChanges();
            }
            else
            {
                return "failed";
            }

            return "success";
        }

        // Delete: Library
        public IActionResult DeleteLibrary(int id)
        {
            var dlt = db.Libraries.Where(n => n.ID == id).FirstOrDefault();
            return View(dlt);
        }

        [HttpPost]
        public string DeleteLibrary(Library library)
        {
            
            var message = string.Empty;
            try
            {
                var libDel = db.Libraries.Find(library.ID);
                db.Libraries.Remove(libDel);
                db.SaveChanges();
                message = "success";
            }
            catch (Exception aa)
            {
                message = aa.Message;
            }
            return message;
        }
        [HttpPost]
        public JsonResult GetLibraries(DataManagerRequest dm)
        {
            var library = db.Libraries.AsNoTracking().Select(s => new
            {    s.ID,
                 s.LibraryName,
                 s.Campus.CampusName,
                 s.Code,
                 OpeningTime = s.OpeningTime.ToString(),
                 ClosingTime = s.ClosingTime.ToString()
            });
            DataOperations operation = new DataOperations();
            if (dm.Search != null && dm.Search.Count > 0)
            {
                library = operation.PerformSearching(library, dm.Search);  //Search
            }
            if (dm.Sorted != null && dm.Sorted.Count > 0) //Sorting
            {
                library = operation.PerformSorting(library, dm.Sorted);
            }
            if (dm.Where != null && dm.Where.Count > 0) //Filtering
            {
                library = operation.PerformFiltering(library, dm.Where, dm.Where[0].Operator);
            }
            int count = library.Count();
            if (dm.Skip != 0)
            {
                library = operation.PerformSkip(library, dm.Skip);   //Paging
            }
            if (dm.Take != 0)
            {
                library = operation.PerformTake(library, dm.Take);
            }
            if (dm.RequiresCounts)
            {
                return Json(new { result = library, count = library.Count() });
            }
            else
            {
                return Json(new { result = library, count = library.Count() });
            }
        }


        // GET: BookList
        public IActionResult BookList()
        {
            return View();
        }

        [HttpPost]
        public string BookList(LibraryBookList bookList)
        {
            bookList.IsIssuable = true;
            try
            {
                bookList.EntryDate = DateTime.Now;
                db.LibraryBookLists.Add(bookList);
                db.Entry(bookList).State = EntityState.Added;
                db.SaveChanges();
                return "success";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        [HttpPost]
        public JsonResult GetBookList(DataManagerRequest request)
        {
            var booklist = db.LibraryBookLists.Select(s => new {
                s.ID,
                s.AccessionNo,
                s.ClassficationNo,
                s.Title,
                s.Author,
                s.Publisher,
                s.Edition,
                s.Subject,
                s.YearOfPublishing,
                s.VolumeNo,
                s.Language,
                s.Pages,
                s.Price,
                s.Source,
                s.PresentPosition,
                s.Remarks,
                s.Translator,
                EntryDate = s.EntryDate.ToString(),
                s.Cornor,
            });
            DataOperations operations = new DataOperations();
            if(request.Search !=null && request.Search.Count > 0)
            {
                booklist = operations.PerformSearching(booklist, request.Search);
            }
            if(request.Sorted !=null && request.Sorted.Count> 0)
            {
                booklist = operations.PerformSorting(booklist, request.Sorted);
            }
            if(request.Where !=null && request.Where.Count>0)
            {
                booklist = operations.PerformFiltering(booklist, request.Where, request.Where[0].Operator);
            }
            int count = booklist.Count();
            if (request.Skip !=0)
            {
                booklist = operations.PerformSkip(booklist, request.Skip);
            }
            if(request.Take != 0)
            {
                booklist = operations.PerformTake(booklist, request.Take);
            }
            if (request.RequiresCounts)
            {
                return Json(new { result = booklist, count = booklist.Count() });
            }
            else
            {
                return Json(new { result = booklist, count = booklist.Count() });
            }
            
        }

        // Edit: BookList
        public ActionResult EditBookList(int id)
        {
            var list = db.LibraryBookLists.Where(n => n.ID == id).FirstOrDefault();
            return View(list);
        }

        [HttpPost]
        public string EditBookList(LibraryBookList list)
        {
            var staffEdit = db.LibraryBookLists.Find(list.ID);
            if (staffEdit != null)
            {
                staffEdit.AccessionNo = list.AccessionNo;
                staffEdit.ClassficationNo = list.ClassficationNo;
                staffEdit.Title = list.Title;
                staffEdit.Author = list.Author;
                staffEdit.Publisher = list.Publisher;
                staffEdit.Edition = list.Edition;
                staffEdit.Subject = list.Subject;
                staffEdit.YearOfPublishing = list.YearOfPublishing;
                staffEdit.VolumeNo = list.VolumeNo;
                staffEdit.Language = list.Language;
                staffEdit.Pages = list.Pages;
                staffEdit.Price = list.Price;
                staffEdit.Source = list.Source;
                staffEdit.PresentPosition = list.PresentPosition;
                staffEdit.Remarks = list.Remarks;
                staffEdit.Translator = list.Translator;
                staffEdit.Cornor = list.Cornor;
                db.SaveChanges();
            }
            else
            {
                return "failed";
            }

            return "success";
        }

        // Delete: BookList
        public ActionResult DeleteBookList(int id)
        {
            var ff = db.LibraryBookLists.Where(w => w.ID == id).FirstOrDefault();
            return View(ff);
        }

        [HttpPost]
        public async Task<string> DeleteBookList(LibraryBookList bookList)
        {
            var bookListDlt = db.LibraryBookLists.Find(bookList.ID);
            if (bookListDlt != null)
                try
                {
                    var librBookRecords = db.LibraryBookRecords.Where(w => w.LibraryBookListId == bookListDlt.ID)
                        .ToList();
                    var libraryIssuedBooks = db.LibraryIssuedBooks.Where(w => w.LibraryBookRecordId == bookListDlt.ID)
                        .ToList();
                    foreach (var item in librBookRecords)
                    {
                        if (item.LibraryIssuedBooksToStaffs != null)
                            foreach (var issuedtostaff in item.LibraryIssuedBooksToStaffs)
                                db.LibraryIssuedBooksToStaffs.Remove(issuedtostaff);
                        db.LibraryBookRecords.Remove(item);
                    }

                    foreach (var item in libraryIssuedBooks) db.LibraryIssuedBooks.Remove(item);
                    db.LibraryBookLists.Remove(bookListDlt);

                    await db.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    return ex.Message;
                }
            else
                return "failed";

            return "delete";
        }

        // GET: BookRecord
        public ActionResult BooksRecord()
        {
            ViewBag.LibraryId = new SelectList(db.Libraries, "ID", "LibraryName");
            ViewBag.LibraryBookListId = new SelectList(db.LibraryBookLists, "ID", "Title");
            return View();
        }

        [HttpPost]

smsCore/Views/Library/BooksIssued.cshtml
@model Models.LibraryIssuedBook
@inject StaticResources resourse;
@{
    ViewBag.Title = "BooksIssued";
}

<div class="breadcrumbs ace-save-state" id="breadcrumb">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home ace-icon home-icon">

            </i>
            <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
        </li>
        <li class="active">
            Add Book Issued List
        </li>

    </ul>
</div>


<div class="container" id="BookIssued">
   @* @using (Ajax.BeginForm("BooksIssued", "Library", new AjaxOptions { HttpMethod = "POST", OnComplete = "completed", OnSuccess = "reloadGridData", LoadingElementId = "addLibraryIssuedForm #server-progress", OnBegin = "begin" }, new { id = "addLibraryIssuedForm", enctype = "multipart/form-data", data_reset = "true" }))
    {*@
    <form asp-action="BooksIssued" asp-controller="Library" data-ajax="true" data-ajax-method="post" enctype="multipart/form-data" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="addLibraryIssuedForm" data_reset="true">
     
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row">
            <div class="col-12">
                <div id="message">

                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Create Book</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-4  has-feedback">
                        <label>Books </label>
                        <div  class="controls">
                            @Html.DropDownListFor(model => model.LibraryBookRecordId, (SelectList)ViewBag.librarybookList, new { @class = "form-control has-feedback-left" })
                                                <span class="fa fa-phone form-control-feedback left" aria-hidden="true"></span>
                                                @Html.ValidationMessageFor(model => model.LibraryBookRecordId)
                                            </div>
                    </div>

                    <div class="col-12 col-sm-4  has-feedback">
                        <label>Student Name </label>
                        <div  class="controls">
                            @Html.DropDownListFor(model => model.StudentID, (SelectList)ViewBag.StudentID, new { @class = "form-control has-feedback-left" })
                            <span class="fa fa-mobile form-control-feedback left" aria-hidden="true"></span>
                            @Html.ValidationMessageFor(model => model.StudentID)
                        </div>
                    </div>

                    <div class="col-12 col-sm-4 has-feedback">
                        <label>Book Condition </label><font class="text-danger">*</font>
                                                      <div  class="controls">
                                                          @Html.TextBoxFor(model => model.BookCondition, new { @class = "form-control has-feedback-left", required = "true", type = "text" })
                                                          <span class="fa fa-mobile form-control-feedback left" aria-hidden="true"></span>
                                                          @Html.ValidationMessageFor(model => model.BookCondition)
                                                      </div>
                    </div>

                    @Html.Partial("_PartialDate", new PartialDateViewModels
                    {
                        Label = "Issued Date",
                        ParentContainerID = "adm-date",
                        ColCssClass = "col-12 col-sm-4",
                        ShowAltField = false,
                        DateFieldId = "IssuedDate",
                        DateFieldName = "IssuedDate",
                        KeepDataFieldReadOnly = true,
                        DefaultDate = DateTime.Now
                    })
                    @Html.Partial("_PartialDate", new PartialDateViewModels
                    {
                        Label = "Due Date",
                        ParentContainerID = "adm-date",
                        ColCssClass = "col-12 col-sm-4",
                        ShowAltField = false,
                        DateFieldId = "DueDate",
                        DateFieldName = "DueDate",
                        KeepDataFieldReadOnly = true
                    })
                    @Html.Partial("_PartialDate", new PartialDateViewModels
                    {
                        Label = "Return Date",
                        ParentContainerID = "adm-date",
                        ColCssClass = "col-12 col-sm-4",
                        ShowAltField = false,
                        DateFieldId = "ReturnDate",
                        DateFieldName = "ReturnDate",
                        KeepDataFieldReadOnly = true
                    })



                    <div class="col-12 col-sm-4 has-feedback">
                        <label>Remarks </label><font class="text-danger">*</font>
                                               <div  class="controls">
                                                   @Html.TextBoxFor(model => model.Remarks, new { @class = "form-control has-feedback-left", required = "true", type = "text" })
                                                   <span class="fa fa-mobile form-control-feedback left" aria-hidden="true"></span>
                                                   @Html.ValidationMessageFor(model => model.Remarks)
                                               </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-12">
                        <button type="submit" value="Create" name="Update" id="updatebtn" class="btn btn-primary float-right mt-4 mr-2 m-md-2">
                            <i class="fa fa-save mr-2"></i>
                            <span>
                                <i id="server-progress" style="display: none;" class=" fa fa-spinner fa-spin "></i>
                            </span> Save
                        </button>
                    </div>
                </div>

            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Issued Book List</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
  @*                      @Html.EJS().Grid("list").AllowFiltering().FilterSettings(filter => filter.Type(FilterType.Menu)).AllowGrouping().Height("300").Width("auto").AllowExcelExport().AllowPdfExport().ShowColumnMenu().ShowColumnChooser().AllowResizing().Columns(col =>
                        {
                        col.Field("Bookname").HeaderText("Book Name").Width("60").TextAlign(TextAlign.Left).Add();
                        col.Field("StudentID").HeaderText("Student Name").Width("120").TextAlign(TextAlign.Left).Add();
                        col.Field("BookCondition").HeaderText("Book Condition").Width("60").TextAlign(TextAlign.Left).Add();
                        col.Field("IssuedDate").HeaderText("Issued Date").Width("60").TextAlign(TextAlign.Left).Add();
                        col.Field("DueDate").HeaderText("Due Date").Width("80").TextAlign(TextAlign.Left).Add();
                        col.Field("ReturnDate").HeaderText("Return Date").Width("80").TextAlign(TextAlign.Left).Add();
                        col.Field("Remarks").HeaderText("Remarks").Width("80").TextAlign(TextAlign.Left).Add();
                        col.Field("action").Template("#action").HeaderText("Action").Width("70").TextAlign(TextAlign.Left).Add();
                        }).AllowPaging().PageSettings(page => page.PageSize(10)).Toolbar(new List<string> { "PdfExport", "Print", "ExcelExport", "ColumnChooser", "Search" }).Render()*@
                        @{
                            var modelgrid = new GridModel()
            {
                GridId = "list",
                AllowExcelExport = true,
                AllowPdfExport = true,
                AllowGrouping = true,
                Width = "auto",
                Height = "auto",
                ShowHeader = false,
                Columns = new List<Column>
                        {
                        new Column{FieldName="bookname",HeaderText="Book Name",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                        new Column{FieldName="studentID",HeaderText="Student Name",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                        new Column{FieldName="bookCondition",HeaderText="Book Condition",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                        new Column{FieldName="issuedDate",HeaderText="Entry Date",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                        new Column{FieldName="dueDate",HeaderText="Due Date",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                        new Column{FieldName="remarks",HeaderText="Remarks ",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                        new Column{FieldName="action",Template="#action",HeaderText="Action",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},

                        },
                AllowFiltering = true,
            };
                        }
                        @await Html.PartialAsync("_grid",modelgrid)
                    </div>
                    <script type="text/x-jsrender" id="action">
                        <a title="Edit" id="${ID}" href="/Library/EditBookIssue/${ID}"><i class="fa fa-edit"></i></a>                        
                        <a title="Delete" class="delete" id="${ID}" href="/Library/DeleteBookIssue/${ID}"><i class="fa fa-trash ml-2"></i></a>
                        
                    </script>
                </div>

            </div>
        </div>
    </form>
</div>
 <script @resourse.JavaScript>

    $(document).ready(function () {
        var url = '@Url.Action("GetIssuedBooks")';
        var grid = document.getElementById("list").ej2_instances[0];
        grid.dataSource = [];
        grid.dataSource = new ej.data.DataManager({
            url: url,
            adaptor: new ejs.data.UrlAdaptor()
        });
    });

    function reloadGridData() {
        var gird = document.getElementById('list').ej2_instances[0];
        gird.refresh();
    }
    // Modal For Delete Issued Book List //
    $('#list').on('click',
        'a.delete',
        function (e) {
            e.preventDefault();
            var title = 'Issued Book Delete';
            var url = $(this).attr('href');

            BootstrapDialog.show({
                title: title,
                message: $('#bootstrap-diallog').html('<div />').load(url),
                onhide: function (dialogRef) {
                    $('body').append('<div id="bootstrap-diallog"></div>');
                    reloadGridData();
                }
            });
            return false;
        });

</script>

smsCore/Views/Library/BooksRecord.cshtml
@model Models.LibraryBookRecord
@inject StaticResources resourse;
@{
    ViewBag.Title = "BooksRecord";
}

<div class="breadcrumbs ace-save-state" id="breadcrumb">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home ace-icon home-icon">

            </i>
            <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
        </li>
        <li class="active">
            Add Book List
        </li>

    </ul>
</div>


<div class="container" id="BookRecords">

   @* @using (Ajax.BeginForm("BooksRecord", "Library", new AjaxOptions { HttpMethod = "POST", OnComplete = "completed", OnSuccess = "reloadGridData", LoadingElementId = "addLibraryRecordForm #server-progress", OnBegin = "begin" }, new { id = "addLibraryRecordForm", enctype = "multipart/form-data", data_reset = "true" }))
    {*@
    <form asp-action="BooksRecord" asp-controller="Library" data-ajax="true" data-ajax-method="post" enctype="multipart/form-data" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="addLibraryIssuedForm" data_reset="true">
  
     
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)


        <div class="row">
            <div class="col-12">
                <div id="message">

                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Add Book List</h3>
            </div>
            <div class="card-body">
                <div class="row">


                    <div class="col-12 col-sm-3  has-feedback">
                        <label>Library Name </label>
                        <div  class="controls">
                            @Html.DropDownListFor(model => model.LibraryId, (SelectList)ViewBag.LibraryId, new { @class = "form-control has-feedback-left" })
                                                <span class="fa fa-phone form-control-feedback left" aria-hidden="true"></span>
                                                @Html.ValidationMessageFor(model => model.LibraryId)
                                            </div>
                    </div>
                    <div class="col-12 col-sm-3  has-feedback">
                        <label>Book List </label>
                        <div  class="controls">
                            @Html.DropDownListFor(model => model.LibraryBookListId, (SelectList)ViewBag.LibraryBookListId, new { @class = "form-control has-feedback-left" })
                                                <span class="fa fa-mobile form-control-feedback left" aria-hidden="true"></span>
                                                @Html.ValidationMessageFor(model => model.LibraryBookListId)
                                            </div>
                    </div>
                    <div class="col-12 col-sm-3 has-feedback">
                        <label>Shelf No </label>
                        <div  class="controls">
                            @Html.TextBoxFor(model => model.ShelfNo, new { @class = "form-control has-feedback-left", required = "true", type = "text" })
                            <span class="fa fa-mobile form-control-feedback left" aria-hidden="true"></span>
                            @Html.ValidationMessageFor(model => model.ShelfNo)
                        </div>
                    </div>

                    @Html.Partial("_PartialDate", new PartialDateViewModels
                    {
                        Label = "Entry Date",
                        ParentContainerID = "adm-date",
                        ColCssClass = "col-12 col-sm-3 date",
                        ShowAltField = false,
                        DateFieldId = "EntryDate",
                        DateFieldName = "EntryDate",
                        KeepDataFieldReadOnly = true,
                        DefaultDate = DateTime.Now
                    })

                </div>

                <div class="row">
                    <div class="col-12">
                        <button type="submit" value="Create" name="Update" id="updatebtn" class="btn btn-primary float-right mt-5 mr-2 m-md-2">
                            <i class="fa fa-save mr-2"></i>
                            <span>
                                <i id="server-progress" style="display: none;" class=" fa fa-spinner fa-spin "></i>
                            </span> Save
                        </button>
                    </div>
                </div>

            </div>
        </div>


        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Library Books Record List</h3>
            </div>
            <div class="card-body">
                <div class="col-12">
        @*            @Html.EJS().Grid("list").AllowFiltering().FilterSettings(filter => filter.Type(FilterType.Menu)).AllowGrouping().Height("300").Width("auto").AllowExcelExport().AllowPdfExport().ShowColumnMenu().ShowColumnChooser().AllowResizing().Columns(col =>
                    {
                    col.Field("Library").HeaderText("Library Name").Width("60").TextAlign(TextAlign.Left).Add();
                    col.Field("Book").HeaderText("Book Name").Width("120").TextAlign(TextAlign.Left).Add();
                    col.Field("ShelfNo").HeaderText("Shelf No").Width("60").TextAlign(TextAlign.Left).Add();
                    col.Field("EntryDate").HeaderText("Entry Date").Width("60").TextAlign(TextAlign.Left).Add();
                    col.Field("action").Template("#action").HeaderText("Action").Width("70").TextAlign(TextAlign.Left).Add();
                    }).AllowPaging().PageSettings(page => page.PageSize(10)).Toolbar(new List<string> { "PdfExport", "Print", "ExcelExport", "ColumnChooser", "Search" }).Render()*@
                    @{
                        var modelgrid = new GridModel()
            {
                GridId = "list",
                AllowExcelExport = true,
                AllowPdfExport = true,
                AllowGrouping = true,
                Width = "auto",
                Height = "auto",
                ShowHeader = false,
                Columns = new List<Column>
                    {
                    new Column{FieldName="library",HeaderText="Library Name",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="book",HeaderText="Book Name",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="shelfNo",HeaderText="Shelf No",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="entryDate",HeaderText="Entry Date",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="action", Template="#action",HeaderText="Action",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
       
                    },
                AllowFiltering = true,
            };
                    }
                    @await Html.PartialAsync("_grid",modelgrid)
                </div>
                <script type="text/x-jsrender" id="action">
                    <a title="Edit" class="editL" id="${ID}" href="/Library/EditBookRecord/${ID}"><i class="fa fa-edit"></i></a>
                    <a title="Delete" class="delete" id="${ID}" href="/Library/DeleteBookRecord/${ID}"><i class="fa fa-trash ml-2"></i></a>

                </script>
            </div>
        </div>
    </form>
</div>
 <script @resourse.JavaScript>
      $(document).ready(function () {
        var url2 = '@Url.Action("GetBooksRecord")';
        var grid = document.getElementById("list").ej2_instances[0];
        grid.dataSource = [];
        grid.dataSource = new ej.data.DataManager({
            url: url2,
            adaptor: new ejs.data.UrlAdaptor()
        });
      });

    function reloadGridData() {
        var gird = document.getElementById('list').ej2_instances[0];
        gird.refresh();
    }

    function Add() {
        var title = "Add Books Record";
        var url = '@Url.Action("BooksRecord", "Library")';
        BootstrapDialog.show({
            title: title,
            message: $('<div />').load(url),
            onhide: function(dialogRef) {
                reloadGridData();
            }
        });
    }

    //Modal for Edit Library 
    $('#list').on('click',
        'a.editL',
        function (e) {
            e.preventDefault();
            var title = 'Edit Library';
            var url = $(this).attr('href');

            BootstrapDialog.show({
                title: title,
                message: $('#bootstrap-diallog').html('<div />').load(url),
                onhide: function (dialogRef) {
                    $('body').append('<div id="bootstrap-diallog"></div>');
                    reloadGridData();
                }
            });
            return false;
        });

    // Modal For Delete Staff Issued Book List //
    $('#list').on('click',
        'a.delete',
        function (e) {
            e.preventDefault();
            var title = 'Staff Issued Book Delete';
            var url = $(this).attr('href');

            BootstrapDialog.show({
                title: title,
                message: $('#bootstrap-diallog').html('<div />').load(url),
                onhide: function (dialogRef) {
                    $('body').append('<div id="bootstrap-diallog"></div>');
                    reloadGridData();
                }
            });
            return false;
        });
</script>