smsCore/Controllers/MessageController.cs
using System.Collections;
using System.Data;
using Hangfire;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Models;
using SchoolManagementSystem.Helpers;
using sms.Hubs;
using smsCore;
using smsCore.Controllers;
using smsCore.Data.Helpers;
using smsCore.Data.Models.ViewModels;
using Syncfusion.EJ2.Base;
using Utilities;

namespace msCore.Controllers
{
    //[CompressContent]
   // [System.Web.Mvc.Authorize]
    public class MessageController : BaseController
    {
        #region private variable
        private readonly DatabaseAccessSql dba;
        private readonly SchoolEntities db;
        private readonly StaticResources _st;
        private readonly MessagingSystem ms;
        private readonly UtilityFunctions _utitlity;
        private readonly ClsBussinessSetting setting;
        private readonly IHubContext<SmsHub> hubContext;

        public MessageController(SchoolEntities _db, DatabaseAccessSql sq, StaticResources st,MessagingSystem _ms, UtilityFunctions utitlity, ClsBussinessSetting _setting,IHubContext<SmsHub> _hub)
        {
            db = _db;
            dba = sq;
            _st = st;
            ms = _ms;
            _utitlity = utitlity;
            setting = _setting;
            hubContext = _hub;
        }
        #endregion

        private static void SendNotification(IHubContext<SmsHub> context, object data)
        {
            //context.Clients.Group(HubSubscriptions.FeeEntry.ToString()).notification(data);
            context.Clients.All.SendCoreAsync("notification",new object[] { data });
        }

        #region MessageSubscribtion

        [HttpGet]
        public IActionResult MessageSubscribtion()
        {
            return View();
        }

        
        [HttpPost]
        public string MessageSubscribtion(MessageRecord message)
        {
            var msg = string.Empty;
            var data = new DataTable();
            var cmbClass = Request.Form["Classes"];
            var cmbCampus = Request.Form["Campus" +
                                         ""];
            var cmbSection = Request.Form["Sections"];

            var clsID = cmbClass == "all" ? 0 : int.Parse(cmbClass);

            int[] campid = {int.Parse(cmbCampus)};

            int[] secid = {0};

            try
            {
                secid[0] = int.Parse(cmbSection);
            }
            catch
            {
            }

            if (cmbSection == "0" || cmbSection== "all")
            {
                if (clsID > 0)
                    secid = db.ClassSections.Where(w => w.ClassID == clsID).Select(s => s.ID).ToArray();
                else
                    secid = db.ClassSections.Select(s => s.ID).ToArray();
            }

            if (cmbCampus == "0") campid = db.Campuses.Select(s => s.ID).ToArray();

            var q =
                "SELECT TOP (100) PERCENT dbo.Students.RegistrationNo, dbo.Students.StudentName, dbo.Students.FName, dbo.Classes.ClassName, dbo.Sections.SectionName, dbo.Campuses.CampusName, CONVERT(bit, dbo.ComSubs.Attendance) as Attendance , Convert(bit ,dbo.ComSubs.Result) as Result, Convert(bit,dbo.ComSubs.IssuedFee) as IssuedFee, Convert(bit, dbo.ComSubs.ReceiveFee) as ReceiveFee FROM dbo.Admissions INNER JOIN dbo.Students ON dbo.Admissions.StudentID = dbo.Students.ID INNER JOIN dbo.ClassSections ON dbo.Admissions.ClassSectionID = dbo.ClassSections.ID LEFT OUTER JOIN dbo.ComSubs ON dbo.Students.ID = dbo.ComSubs.StudentID INNER JOIN dbo.Campuses ON dbo.Admissions.CampuseID = dbo.Campuses.ID INNER JOIN dbo.Classes ON dbo.ClassSections.ClassID = dbo.Classes.ID INNER JOIN dbo.Sections ON dbo.ClassSections.SectionID = dbo.Sections.ID WHERE (dbo.Admissions.IsExpell = 0) AND (dbo.ClassSections.ID IN (" +
                string.Join(",", secid) + ")) AND ( dbo.Campuses.ID IN (" + string.Join(",", campid) +
                ")) ORDER BY dbo.Students.RegistrationNo";

            //var dba = new DatabaseAccessSql();

            data = dba.CreateTable(q);

            if (data.Rows.Count < 0) msg = "No data found to display";


            var total = data.Rows.Count + " out of " + db.Admissions.Where(w => w.IsExpell == false).Count();
            ViewBag.labeltotal = total;
            //return View(data);
            return msg;
        }

        public IActionResult MessageSubscribtionList(DataManagerRequest request, int campid, int secid, int clsid)
        {
            var q =
                @"SELECT dbo.Students.ID as StudentId, dbo.Students.RegistrationNo, dbo.Students.StudentName, dbo.Students.FName, dbo.Classes.ClassName, dbo.Sections.SectionName, 
dbo.Campuses.CampusName, CONVERT(bit, Isnull(dbo.ComSubs.Attendance,0)) as Attendance , Convert(bit ,Isnull(dbo.ComSubs.Result,0)) as Result, 
Convert(bit,Isnull(dbo.ComSubs.IssuedFee,0)) as IssuedFee, Convert(bit, Isnull(dbo.ComSubs.ReceiveFee,0)) as ReceiveFee 
FROM dbo.Admissions INNER JOIN dbo.Students ON dbo.Admissions.StudentID = dbo.Students.ID INNER JOIN 
dbo.ClassSections ON dbo.Admissions.ClassSectionID = dbo.ClassSections.ID LEFT OUTER JOIN dbo.ComSubs ON 
dbo.Students.ID = dbo.ComSubs.StudentID INNER JOIN dbo.Campuses ON dbo.Admissions.CampuseID = dbo.Campuses.ID INNER JOIN 
dbo.Classes ON dbo.ClassSections.ClassID = dbo.Classes.ID INNER JOIN dbo.Sections ON dbo.ClassSections.SectionID = dbo.Sections.ID 
WHERE (dbo.Admissions.IsExpell = 0) AND (dbo.ClassSections.ClassID IN (" + string.Join(",", clsid) +
                ")) AND(dbo.ClassSections.SectionID IN (" + string.Join(",", secid) + ")) AND ( dbo.Campuses.ID IN (" +
                string.Join(",", campid) + ")) " +
                "ORDER BY dbo.Students.RegistrationNo ";


            

            var table = dba.CreateTable(q).AsEnumerable().Select(s=>new { 
                RegistrationNo = s.Field<int>("RegistrationNo"),
                StudentName = s.Field<string>("StudentName"),
                FName = s.Field<string>("FName"),
                Attendance = s.Field<bool>("Attendance"),
                Result = s.Field<bool>("Result"),
                ReceiveFee = s.Field<bool>("ReceiveFee"),
                IssuedFee = s.Field<bool>("IssuedFee"),
                StudentId = s.Field<int>("StudentId")
            });
           
            return Json(new { result= table, count = table.Count() });

        }

        [HttpPost]
        public async Task<JsonResult> MessageSubscription(List<MessageSubscriptionViewModel> changed)
        {
            foreach (var e in changed)
            {
                var exist = db.ComSubs.FirstOrDefault(w => w.StudentID == e.StudentId);
                if (exist == null)
                {
                    exist = new ComSub() { StudentID = e.StudentId };
                    db.ComSubs.Add(exist);
                }

                exist.Attendance = e.Attendance ? 1 : 0;
                exist.IssuedFee = e.IssuedFee ? 1 : 0;
                exist.ReceiveFee = e.ReceiveFee ? 1 : 0;
                exist.Result = e.Result ? 1 : 0;

            }

            try
            {
                await db.SaveChangesAsync();
                return Json(new { status = true, message = "Data saved successfully." });
            }
            catch
            {
                return Json(new { status = false, message = "Failed to save data." });
            }

        }

     
        #endregion

        #region Send Message by Student Name

        public IActionResult SendMessagebyStudentName()
        {
            return View();
        }


        public void SendMessagebyStudentNamesTask(List<BulkMessageViewModel> records)
        {
            SendNotification(hubContext, _st.QeuedReturn("Send Message Task", StaticResources.ToastType.info, "Task Started.", 0, false));
            int total = records.Count;
            int per_page = 40;
            bool sent = false;
            for (int i = 0; i < total;)
            {
                var page = records.Skip(i).Take(per_page).Select(s => s.Mobile).ToArray();
                if (page.Count() > 0)
                    sent = ms.sendMessage(records[0].Message, page, records[0].IsRtl).Result;
                SendNotification(hubContext, _st.QeuedReturn("Send Message Task", StaticResources.ToastType.info, "Sending messages to students.", i , false));
                i += per_page;
            }

            SendNotification(hubContext, _st.QeuedReturn("Send Message Task", StaticResources.ToastType.info, "Task Completed.", 100, true));

        }

        [HttpPost]
        public JsonResult SendMessagebyStudentNames(List<BulkMessageViewModel> records)
        {
            var errormessage = string.Empty;

            if (!string.IsNullOrEmpty(ms.error)) return Json(new { status = false, message = ms.error });

            if (records.Count == 0)
                return Json(new { status = false, message = "No data found" });

            try
            {
                BackgroundJob.Enqueue(() => SendMessagebyStudentNamesTask(records));
                return Json(new { status = true, message = _st.QeuedMessage });
            }
            catch (Exception e)
            {
                errormessage = e.Message;
            }

            return Json(new { status = errormessage == "success", message = errormessage });
        }

        public ActionResult StudentListForBulkMessage(DataManagerRequest request, int regnoinput = -1,
            string mobileinput = "", int clsid = -1, int campid = -1)
        {
            var campus = campid == -1 ? db.Campuses.Select(s => s.ID).ToArray() : new[] {campid};
            var classId = clsid == -1 ? db.Classes.Select(s => s.ID).ToArray() : new[] {clsid};

            var studentdetails = db.Admissions.Where(w =>
                !w.IsExpell && w.Student.StudentMobiles.Count() > 0 && campus.Contains(w.CampuseID) &&
                classId.Contains(w.ClassSection.ClassID)).Select(s=>new {

smsCore/Views/Message/MessageSubscribtion.cshtml
@using sms.Models
@inject StaticResources resourse;
@model System.Data.DataTable

@{
    ViewBag.Title = "Message Subscribtion";
}

@section BreadCrumbs{
    <div class="breadcrumbs ace-save-state" id="breadcrumb">
        <ul class="breadcrumb">
            <li>
                <i class="fa fa-home ace-icon home-icon">

                </i>
                <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>
            <li class="active">
                Message Subscribtion
            </li>

        </ul>
    </div>
}

<style>
    select.form-control { max-height: 30px; }
</style>
<section class="content" id="messagesubscrid">
    <div class="row">
        <div class="col-12">
            @*@using (Ajax.BeginForm("MessageSubscribtion", "Message", new AjaxOptions {HttpMethod = "POST", OnSuccess = "reloadGridData", OnComplete = "completed", LoadingElementId = "MessageSubscribtionmainForm #server-progress", OnBegin = "begin"}, new {id = "MessageSubscribtionmainForm"}))
            {*@
            <form asp-action="MessageSubscribtion" asp-controller="Message" data-ajax="true" OnSuccess="reloadGridData" data-ajax-method="post" enctype="multipart/form-data" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="MessageSubscribtionmainForm" data_reset="true">
                   
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="card">
                    <div class="card-body">

                        <div class="row">
                            <div class="col-12">
                                <div id="message">

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            @Html.Partial("_PartialCampusSelector", new PartialCampusViewModels {ParentContainerID = "messagesubscrid", ColCssClass = "col-md-3 col-sm-4 col-12", ShowCampus = true, ShowClasses = true, ShowSections = true})

                            @*@Html.Partial("_PartialSchoolProperty", new ViewDataDictionary() { { "NoFeeGroup", true }, { "NoSession", true }, { "NoExams", true }, { "NoSubjects", true }, { "NoGroups", true }, { "ColCssClass", "col-12 col-sm-6 col-md-3" } })*@
                            <div class="col-12 col-sm-6 col-md-3 form-group has-feedback pt-4">
                                <button type="button" id="view" name="view" class="btn btn-primary float-right mt-2" onclick="reloadGridData()"><i class="fa fa-search"></i> Search</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title titlefix">Message Subscribtion List <a href="https://www.youtube.com/watch?v=Qf-M08OGFwU&list=UUQFf95Tyl3o9y-DE0vvlTQg" target="_blank" title="Watch our Youtube video to understand" class="btn btn-default btn-sm float-right"><i class="fa fa-question-circle"></i> Help </a></h3>
                    </div>
                    <div class="card-body">
                        <div id="allSelectOption" class="row">
                            <div class="col-12 mb-2">
                                <label class="float-right mr-3"> <input type="checkbox" class="mr-1" name="IssuedFee" id="Check_IssuedFee" value="IssuedFee" />IssuedFee</label>
                                <label class="float-right mr-3"> <input type="checkbox" class="mr-1" name="ReceiveFee" id="Check_ReceiveFee" value="ReceiveFee" />ReceiveFee</label>
                                <label class="float-right mr-3"> <input type="checkbox" class="mr-1" name="Result" id="Check_Result" value="Result" />Result</label>
                                <label class="float-right mr-3">
                                    <input type="checkbox" id="Check_attendences" class="mr-1" name="Attendence" /><span id="Check_attendencesText">Attendence</span>
                                </label>
                                <label class="float-right mr-3">Select All:</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
@*@*
                                @Html.EJS().Grid("list_sms").Columns(col =>
                           {
                               col.Field("RegistrationNo").HeaderText("RegistrationNo").TextAlign(TextAlign.Left).AllowEditing(false).IsPrimaryKey(true).Add();
                               col.Field("StudentName").HeaderText("StudentName").TextAlign(TextAlign.Left).AllowEditing(false).Add();
                               col.Field("FName").HeaderText("FName").TextAlign(TextAlign.Left).AllowEditing(false).Add();
                               col.Field("Attendance").HeaderText("Attendance").TextAlign(TextAlign.Center).DisplayAsCheckBox(true).EditType("booleanedit").Add();
                               col.Field("Result").HeaderText("Result").TextAlign(TextAlign.Center).DisplayAsCheckBox(true).EditType("booleanedit").Add();
                               col.Field("ReceiveFee").HeaderText("ReceiveFee").TextAlign(TextAlign.Center).DisplayAsCheckBox(true).EditType("booleanedit").Add();
                               col.Field("IssuedFee").HeaderText("IssuedFee").TextAlign(TextAlign.Center).DisplayAsCheckBox(true).EditType("booleanedit").Add();
                            }).Height("70vh").Width("auto").EditSettings(e => e.AllowEditing(true).Mode(EditMode.Batch)).Render()*@

                                @{
                                    var modelgrid = new GridModel()
            {
                GridId = "list_sms",
                AllowExcelExport = true,
                AllowPdfExport = true,
                AllowGrouping = true,
                Width = "auto",
                Height = "auto",
                ShowHeader = false,
                Columns = new List<Column>
                                {
                                new Column{FieldName="registrationNo",HeaderText="RegistrationNo",AllowSorting=true,Width="80",HeaderTextAlign=TextAlign.Left},
                                new Column{FieldName="studentName",HeaderText="StudentName",AllowSorting=true,Width="80",HeaderTextAlign=TextAlign.Left},
                                new Column{FieldName="FName",HeaderText="FName",AllowSorting=true,Width="80",HeaderTextAlign=TextAlign.Left},
                                new Column{FieldName="attendance",HeaderText="Attendance",AllowSorting=true,Width="80",HeaderTextAlign=TextAlign.Left},
                                new Column{FieldName="result",HeaderText="Result",AllowSorting=true,Width="80",HeaderTextAlign=TextAlign.Left},
                                new Column{FieldName="issuedFee",HeaderText="IssuedFee",AllowSorting=true,Width="70",HeaderTextAlign=TextAlign.Left},

                                },
                AllowFiltering = true,
            };
                                }
                                @await Html.PartialAsync("_grid",modelgrid)

                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="button" class="btn btn-primary float-right " id="btnSave"><i class="fa fa-save mr-2"></i>Save</button>
                        
                        <label class="float-right mr-2"><input type="checkbox" value="True" /> Send Status Message</label>

                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<script @resourse.JavaScript>

    var grid = document.getElementById("list_sms").ej2_instances[0];
    function reloadGridData() {
        var campid = $('#Campus').val();
        var secid = $('#Sections').val();
        var clsid = $('#Classes').val();
        var url1 = '@Url.Action("MessageSubscribtionList")';
        url1 += '?campid=' + campid + '&secid=' + secid + '&clsid=' + clsid;
        grid.dataSource = new ej.data.DataManager({
            batchUrl:'/Message/MessageSubscription',
            url: url1,
            adaptor: new ejs.data.UrlAdaptor()
        });
    }

   

    $('#btnSave').on('click', function () {
        
        let changes = grid.getBatchChanges();
        console.log(changes);
        if (!changes.changedRecords || changes.changedRecords.length == 0) {
            return false;
        }
        grid.endEdit();
    })
    //attendance check box
    $('#Check_attendences').on('change',
        function () {
            var checked = $(this).is(':checked');
            var data = grid.currentViewData;
            $.each(data, function (i, v) {
                grid.updateCell(i, 'Attendance', checked);
                //grid.setCellValue(v.RegistrationNo, 'Attendance', checked);
            })
        });

    //result check box
    $('#Check_Result').on('change',
        function () {
            var checked = $(this).is(':checked');
            var data = grid.currentViewData;
            $.each(data, function (i, v) { grid.updateCell(i,  'Result', checked); })
        });


    //Issued Fee  Check Box
    $('#Check_IssuedFee').on('change',
        function () {
            var checked = $(this).is(':checked');
            var data = grid.currentViewData;
            $.each(data, function (i, v) { grid.updateCell(i,  'IssuedFee', checked); })
        });


    //Receive Check Box
    $('#Check_ReceiveFee').on('change',
        function () {
            var checked = $(this).is(':checked');
            var data = grid.currentViewData;
            $.each(data, function (i, v) { grid.updateCell(i,  'ReceiveFee', checked); })
        });



</script>

smsCore/Views/Message/SendAttendence.cshtml
@model System.Data.DataTable
@inject StaticResources resourse;

@{
    ViewBag.Title = "Send Attendence";
}

@section BreadCrumbs{
    <div class="breadcrumbs ace-save-state" id="breadcrumb">
        <ul class="breadcrumb">
            <li>
                <i class="fa fa-home ace-icon home-icon">

                </i>
                <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>
            <li class="active">
                Send Attendance Message
            </li>

        </ul>
    </div>
}

@*@using (Ajax.BeginForm("SendAttendence", "Message", new AjaxOptions { HttpMethod = "POST", OnSuccess = "reloadGridData", OnComplete = "completed", LoadingElementId = "SendAttendencemainForm #server-progress", OnBegin = "begin" }, new { id = "SendAttendencemainForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)*@
<form asp-action="SendAttendence" asp-controller="Message" data-ajax="true" data-ajax-method="post" OnSuccess = "reloadGridData" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="SendAttendencemainForm" data_reset="true">

<section class="content" id="student-attandance-container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Attendance List <a href="https://www.youtube.com/watch?v=Qf-M08OGFwU&list=UUQFf95Tyl3o9y-DE0vvlTQg#t=270s" target="_blank" title="Watch our Youtube video to understand" class="btn btn-default btn-sm float-right"><i class="fa fa-question-circle"></i> Help </a>

                    </h3>
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col-12">
                            <div id="message">

                            </div>
                        </div>

                        @await Html.PartialAsync("_PartialCampusSelector", new PartialCampusViewModels { ParentContainerID = "student-attandance-container", ColCssClass = "col-12 col-sm-4 col-md-3", ShowCampus = true, ShowClasses = true, ShowSections = true })


                        <div class="col-12 my-3">
                            <button type="button" class="btn btn-primary float-right" id="search" onclick="reloadGridData();">
                                <i class="mr-2 fa fa-search ">Search</i>
                            </button>
                        </div>
                    </div>

                    <div class="row">
                        <div id="SendAttendence-gridContainer" class="col-12">
                  @*          @Html.EJS().Grid("list_att_message").SelectionSettings(sel => { sel.CheckboxOnly(true); }).Columns(col =>
                       {
                           col.Type("checkbox").Width("50").Add();
                           col.Field("RegistrationNo").HeaderText("Reg. No").AutoFit(true).TextAlign(TextAlign.Left).Add();
                           col.Field("StudentName").HeaderText("Name").TextAlign(TextAlign.Left).Add();
                           col.Field("FName").HeaderText("Father's Name").TextAlign(TextAlign.Left).Add();
                           col.Field("AttendanceType").HeaderText("Attendance").AutoFit(true).TextAlign(TextAlign.Left).Add();
                           col.Field("AttendanceDate").HeaderText("Attendance Time").AutoFit(true).Format("dd/MM/yyyy hh:mm a").TextAlign(TextAlign.Left).Add();
                           col.Field("Mobile").HeaderText("Mobile").AutoFit(true).TextAlign(TextAlign.Left).Add();
                       }).Render()*@

                            @{
                                var modelgrid = new GridModel()
            {
                GridId = "list_att_message",
                AllowExcelExport = true,
                AllowPdfExport = true,
                AllowGrouping = true,
                Width = "auto",
                Height = "auto",
                //AddSerialN = true;
                Columns = new List<Column>
                            {
                            new Column{Type="checkbox",Width="50"},
                            new Column{FieldName="registrationNo",HeaderText="Reg. No",AutoFit=true,HeaderTextAlign=TextAlign.Left},
                            new Column{FieldName="studentName",HeaderText="Name",HeaderTextAlign=TextAlign.Left},
                            new Column{FieldName="fName",HeaderText="Father's Name",HeaderTextAlign=TextAlign.Left},
                            new Column{FieldName="attendanceType",HeaderText="Attendance",AutoFit=true,HeaderTextAlign=TextAlign.Left},
                            new Column{FieldName="attendanceDate",HeaderText="Attendance Time",DateFormat="dd/MM/yyyy hh:mm a",AutoFit=true,HeaderTextAlign=TextAlign.Left},
                            new Column{Template="mobile",HeaderText="Mobile",AutoFit=true,HeaderTextAlign=TextAlign.Left},

                            },
                AllowFiltering = true,
            };
                            }
                            @await Html.PartialAsync("_grid",modelgrid)
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-12 text-right">
                            <button type="submit" class="btn btn-primary" name="save" onclick="Save()"><i class="fa fa-send mr-2"></i>Sent Message</button>
                         </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</Form>
<script @resourse.JavaScript>
    function loaded() {
        let grid = document.getElementById("list_att_message").ej2_instances[0];
        grid.dataSource = [];
    }
</script>
<script @resourse.JavaScript>
    function reloadGridData() {

        var classid = $('#Classes').val();
        var sectionid = $('#Sections').val();
        var campusid = $('#Campus').val();
        if (!campusid || !sectionid || !classid) {
            return false;
        }

        var url1 = '/Message/AttendenceList';
        url1 += '?classid=' + classid + '&campusid=' + campusid + '&sectionid=' + sectionid;

        var grid = document.getElementById("list_att_message").ej2_instances[0];
        grid.dataSource = [];

        grid.dataSource = new ej.data.DataManager({
            url: url1,
            adaptor: new ejs.data.UrlAdaptor()
        });
    }

    function Save() {

        let url = `/Message/SendAttendence`;
        let campusid = $('#Campus').val();

        let grid = document.getElementById('list_att_message').ej2_instances[0];
        var selected = grid.getSelectedRecords();
        if (selected.length == 0) {
            sweetalert("Plaese select atleast one employee before continue", '', 'error');
            return false;
        }

        block('#student-attandance-container');
        $.post(url, { data: selected, campusid }, function (response) {
            if (response.status) {
                $('#message').html('<span class="float-left alert alert-info w-100">Messages sent successfully.<a class="close" style="top: 4px;position: absolute;right: 7px;" onclick="clearMessage();"><i class="fa fa-close"></i></a></span>');
            }
            else {
                $('#message').html('<span class="float-left alert alert-danger w-100">' + response.message + '.<a class="close" style="top: 4px;position: absolute;right: 7px;" onclick="clearMessage();"><i class="fa fa-close"></i></a></span>');
            }
            $('#student-attandance-container').unblock();
        }).error(function () {
            $('#message').html('<span class="float-left alert alert-danger w-100">Unknow network error occured..<a class="close" style="top: 4px;position: absolute;right: 7px;" onclick="clearMessage();"><i class="fa fa-close"></i></a></span>');
            $('#student-attandance-container').unblock();
        });

    }

</script>

smsCore/Views/Message/_MessagesendresultView .cshtml
@using System.Data
@model System.Data.DataTable
@{
    ViewBag.Title = "Send Result";
    Layout = null;
}

<div class="row no-gutters  mt-1">
    <div class="col-12">
        <table class="table table-bordered table-hover " border="1" id="tbl_results">
            <thead>
            <tr>
                @{ var i = 1; }
                @foreach (DataColumn cols in Model.Columns)
                {
                    if (i == 1)
                    {
                        <th><input type="checkbox" name="selectAll" id="selectAll" class="mr-2" /></th>
                    }
                    <th>
                        @cols.Caption
                    </th>
                    i++;
                }
            </tr>
            </thead>
            <tbody>
            @foreach (DataRow dr in Model.Rows)
            {
                <tr>
                    @{ var j = 1; }
                    @foreach (DataColumn cols in Model.Columns)
                    {
                        if (j == 1)
                        {
                            <td>
                                <input type="checkbox"class="select-row" />
                            </td>
                        }
                        <td>
                            @if (j == 1)
                            {
                                <input type="hidden" name="Regno" value="@dr[cols.ColumnName].ToString()" disabled/>
                            }
                            @dr[cols.ColumnName].ToString()
                        </td>
                        j++;
                    }
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>
<script>
    $('.select-row').each(function () {
        $(this).on('change', function () {
            var val = $(this).is(':checked');
            if (val)
                $(this).closest('tr').find('input[name="Regno"]').removeAttr('disabled');
            else
                $(this).closest('tr').find('input[name="Regno"]').attr('disabled', 'true');
        })
    })

    $('#selectAll').on('change', function () {
        var table = $('#tbl_results');
        $('td input:checkbox', table).prop('checked', this.checked);
        var chk = this.checked;
        $('#tbl_results td input[name="Regno"]').each(function () {
            if (chk)
                $(this).removeAttr('disabled');
            else
                $(this).attr('disabled', 'true');

        })
    });
</script>