smsCore/Controllers/FeeController.cs
using System.Collections;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models;
using smsCore.BackgroundTasks;
using smsCore.Data;
using smsCore.Data.Helpers;
using smsCore.Data.Models;
using smsCore.Data.Models.ViewModels;
using Syncfusion.EJ2.Base;
using Utilities;

namespace smsCore.Controllers
{
    [Authorize]
    public class FeeController : BaseController
    {
        private readonly SchoolEntities db;
        private readonly CurrentUser _user;
        private readonly SelectListHelper _selectListHelper;
        private readonly StaticResources _resource;
        private readonly MessagingSystem _ms;
        private readonly DatabaseAccessSql dba;
        private readonly LedgerPostingSP _ledgerPosting;
        private readonly int[] _campusIds;//= Helpers.CurrentUser.GetCampusIds();
        AddFeeBackgroundTask _backgroundTask;
        ClsBussinessSetting _setting;
        FeeSystemHelper _helper;


        public FeeController(SchoolEntities _db, CurrentUser user, StaticResources resources, SelectListHelper selectListHelper, MessagingSystem ms, LedgerPostingSP ledgerPosting, DatabaseAccessSql databaseAccessSql, AddFeeBackgroundTask backgroundTask, ClsBussinessSetting setting, FeeSystemHelper helper)
        {
            db = _db;
            _user = user;
            _resource = resources;
            _campusIds = user.GetCampusIds();
            _selectListHelper = selectListHelper;
            _ms = ms;
            _ledgerPosting = ledgerPosting;
            dba = databaseAccessSql;
            _backgroundTask = backgroundTask;
            _setting = setting;
            _helper = helper;
        }
        public IActionResult ClassfeeIndex()
        {
            ViewBag.FeeGroups = _selectListHelper.GetSectionFeeGroupList();
            ViewBag.ClassId = _selectListHelper.GetClassSelectList();
            return View();
        }


        [HttpPost]
        public async Task<string> AddClassFeeGroups(ClassFeeGroup model)
        {
            var message = "failed";
            var fclg = db.ClassFeeGroups.Where(w => w.CampusID == model.CampusID && w.ClassID == model.ClassID)
                .FirstOrDefault();
            if (fclg == null)
            {
                fclg = new ClassFeeGroup();

                fclg.ClassID = model.ClassID;
                fclg.CampusID = model.CampusID;
                db.ClassFeeGroups.Add(fclg);
            }

            fclg.FeeGroupID = model.FeeGroupID;
            try
            {
                await db.SaveChangesAsync();
                message = "success";
            }

            catch (Exception aa)
            {
                message = aa.InnerException != null ? aa.InnerException.Message : aa.Message;
                //ModelState.AddModelError("", aa.Message);
            }

            return message;
        }

        public IActionResult ClassfeeDelete(int? id, bool? saveChangesError = false)
        {
            if (saveChangesError.GetValueOrDefault())
                ViewBag.ErrorMessage =
                    "Delete failed. Try again, and if the problem persists see your system administrator.";
            var clsfee = db.ClassFeeGroups.Find(id);
            if (clsfee == null) return NotFound();
            return View(clsfee);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<string> ClassfeeDelete(int id)
        {
            var message = string.Empty;
            try
            {
                var clsfee = db.ClassFeeGroups.Find(id);
                db.ClassFeeGroups.Remove(clsfee);
                await db.SaveChangesAsync();
                message = "success";
            }
            catch (Exception aa)
            {
                message = aa.Message;
                //ModelState.AddModelError("", aa.Message);
            }

            return message;
        }


        [HttpPost]
        public async Task<JsonResult> ClassFeeGroupList(DataManagerRequest dm, int campusId)
        {
            var types = db.ClassFeeGroups.Include(i=>i.FeeGroup.FeeStructures).Include(i=>i.Class).
                Where(w => w.CampusID == campusId).Select(s => new
            {
                s.ID,
                s.Class.ClassName,
                s.FeeGroup.FeeGroupName,
                Amount = s.FeeGroup.FeeStructures.Where(w => !w.Revised && w.CampusID == campusId && w.FeeGroupId == s.FeeGroupID).Select(t => t.Amount).Sum(),
                s.FeeGroupID,
                s.CampusID
            }).AsEnumerable();

            DataOperations operation = new DataOperations();
            if (dm.Search != null && dm.Search.Count > 0)
            {
                types = operation.PerformSearching(types, dm.Search);  //Search
            }
            if (dm.Sorted != null && dm.Sorted.Count > 0) //Sorting
            {
                types = operation.PerformSorting(types, dm.Sorted);
            }
            if (dm.Where != null && dm.Where.Count > 0) //Filtering
            {
                types = operation.PerformFiltering(types, dm.Where, dm.Where[0].Operator);
            }
            int count = types.Count();
            if (dm.Skip != 0)
            {
                types = operation.PerformSkip(types, dm.Skip);   //Paging
            }
            if (dm.Take != 0)
            {
                types = operation.PerformTake(types, dm.Take);
            }
            //if (dm.RequiresCounts)
            {
                return Json(new { result = types, count = count });
            }
            //else
            {
              //  return Json(types);
            }

        }

        //Class group fee end
        //***********Fee Structure Start********

        public IActionResult FeestructIndex(int campId = 0, int feegroupid = 0)
        {
            if (campId == 0 && feegroupid == 0)
            {
                var CampusId = -1;
                if (_user.BasicUserType == EnumManager.BasicUserType.Campus)
                    CampusId = _user.GetCampusIds().FirstOrDefault();
                else
                    CampusId = CampusId == -1 ? db.Campuses.Select(s => s.ID).FirstOrDefault() : CampusId;
                ViewBag.CampusId = CampusId;
                var select = db.FeeGroups.Select(s => new { s.ID, s.FeeGroupName }).ToList();
                ViewBag.feegrouplist = new SelectList(select, "ID", "FeeGroupName");

                return View();
            }

            ViewBag.CampusId = campId;
            var feegrop = db.FeeGroups.Find(feegroupid);
            ViewBag.feegrouplist = new SelectList(db.FeeGroups.ToList(), "ID", "FeeGroupName", feegroupid);
            ViewBag.FeeGroupId = feegroupid;
            return View();
        }


        public IActionResult FeestructEdit(int id, int feeGroupId, int campusId)
        {
            var feeGroup = db.FeeGroups.Where(w => w.ID == feeGroupId).Select(s => s.FeeGroupName).FirstOrDefault();
            var feetypeModel = db.FeeTypes.Where(w => w.Id == id).FirstOrDefault();
            if (feetypeModel == null || string.IsNullOrEmpty(feeGroup))
                throw new Exception("Inavlid fee type selected.");
            ViewBag.campusId = campusId;
            ViewBag.FeeGroupId = feeGroupId;
            ViewBag.FeeGroupName = feeGroup;
            return View(feetypeModel);
        }

        [HttpPost]
        public async Task<string> FeestructEdit(FeeType model)
        {
            var message = string.Empty;

            var FeeGroupId = int.Parse(Request.Form["FeeGroupId"].ToString());
            var campusId = int.Parse(Request.Form["campusId"].ToString());

            var Feestructure = db.FeeStructures.ToList().Where(w =>
                w.CampusID == campusId && w.FeeTypeId == model.Id && w.FeeGroupId == FeeGroupId && !w.Revised);
            if (Feestructure.Count() > 0 && Feestructure != null)
                foreach (var fee in Feestructure)
                    fee.Revised = true;

            var feeStructures = new FeeStructure();

            feeStructures.Amount = decimal.Parse(Request.Form["Amount"].ToString());
            feeStructures.Deduction = false;
            feeStructures.EffectiveFrom = DateTimeHelper.ConvertDate(Request.Form["EffectiveFrom"].ToString());
            feeStructures.EntryDate = DateTime.Now;
            feeStructures.FeeGroupId = FeeGroupId;
            feeStructures.FeeTypeId = model.Id;
            feeStructures.IsActive = !string.IsNullOrEmpty(Request.Form["IsActive"]);
            feeStructures.IsDeleted = !string.IsNullOrEmpty(Request.Form["IsDeleted"]);
            feeStructures.Revised = false;
            feeStructures.UserId = _user.UserID;
            feeStructures.CampusID = campusId;
            db.FeeStructures.Add(feeStructures);

            try
            {
                await db.SaveChangesAsync();
                message = "success";
            }
            catch (Exception aa)
            {
                message = aa.Message;
            }

            return message;
        }


        public IActionResult FeestructDelete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
            }

            if (saveChangesError.GetValueOrDefault())
                ViewBag.ErrorMessage =
                    "Delete failed. Try again, and if the problem persists see your system administrator.";
            var feestruct = db.FeeStructures.Find(id);
            if (feestruct == null) return NotFound();
            return View(feestruct);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult FeestructDelete(int id)
        {
            try
            {
                var feestruct = db.FeeStructures.Find(id);

smsCore/Views/Fee/ClassfeeIndex.cshtml
@model IEnumerable<Models.ClassFeeGroup>
@inject StaticResources resources

@{
    ViewBag.Title = "Class Fee Groups";
}

<div class="breadcrumbs ace-save-state" id="breadcrumb">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home ace-icon home-icon">

            </i>
            <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
        </li>
        <li class="active">
            Class Fee
        </li>

    </ul>
</div>

<section class="content" id="classfeeindex">
    <div class="row">
        <div class="col-md-4">
            <!-- Horizontal Form -->
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">Class Fee Group <a href="https://www.youtube.com/watch?v=-L7sM_ZtyMo&list=UUQFf95Tyl3o9y-DE0vvlTQg#t=290s" target="_blank" title="Watch our Youtube video to understand" class="btn btn-default btn-sm float-right"><i class="fa fa-question-circle"></i> Help </a></h3>
                </div><!-- /.box-header -->

               @* @using (Ajax.BeginForm("AddClassFeeGroups", "Fee", new AjaxOptions { HttpMethod = "POST", OnSuccess = "reloadGridData", OnComplete = "completed", LoadingElementId = "classFeeIndexmainForm #server-progress", OnBegin = "begin" }, new { id = "classFeeIndexmainForm", data_noreset = "false" })){*@

                <form asp-action="AddClassFeeGroups" asp-controller="Fee" data-ajax="true" data-ajax-method="post" OnSuccess="reloadGridData" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="classFeeIndexmainForm" data_noreset="false">
                   
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div id="message">

                                </div>
                            </div>
                            @await Html.PartialAsync("_PartialCampusSelector", new PartialCampusViewModels { CampusLoadCallBack= "reloadGridData();", ParentContainerID = "classfeeindex", ColCssClass = "col-12 col-sm-12", ShowClasses = true, ShowCampus = true, CampusFieldName = "CampusID", ClassesFieldName = "ClassID" })

                        <div class="col-12 col-sm-12 mt-2">
                            <label> Fee Group:</label><font class="text-danger">*</font>
                            <a class="new float-right" href="@Url.Action("FeeGroupIndex", "Fee")" data-type="fee" title="Add New Fee Group" style="position: inherit !important;">
                                <i class="fa fa-plus"></i>
                            </a>
                            <div class="controls">
                                @Html.DropDownList("FeeGroupID", (SelectList)ViewBag.FeeGroups, new { @class = "form-control has-feedback-left", required = "required" })
                                <span class="fa fa-object-group form-control-feedback left" aria-hidden="true"></span>
                            </div>
                        </div>
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="card-footer mt-2">

                        <button type="submit" value="Create" class="btn btn-primary float-right mb-2">
                            <i class="fa fa-save mr-2"></i>
                            <span>
                                <i id="server-progress" style="display: none;" class=" fa fa-spinner fa-spin "></i>
                            </span> Save
                        </button>
                    </div>
               </form>
            </div>

        </div><!--/.col (right) -->
        <!-- left column -->
        <div class="col-md-8">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header ptbnull">
                    <h3 class="card-title titlefix">Fee Groups List</h3>
                </div><!-- /.box-header -->
                <div class="card-body">
                   @* <div class="col-12">

                        @Html.EJS().Grid("list").Columns(col =>
                   {
                       col.Field("ClassName").HeaderText("Class").TextAlign(TextAlign.Left).Add();
                       col.Field("FeeGroupName").HeaderText("Fee Group").Width("100").TextAlign(TextAlign.Left).Add();
                       col.Field("Amount").HeaderText("Amount").Width("100").TextAlign(TextAlign.Left).Add();
                       col.Field("action").Template("#action").HeaderText("Action").Width("70").TextAlign(TextAlign.Center).Add();
                   }).AllowFiltering().FilterSettings(filter => filter.Type(FilterType.Menu)).Height("auto").Width("auto").AllowExcelExport().AllowPdfExport().ShowColumnMenu().ShowColumnChooser().AllowResizing().PageSettings(page => page.PageSize(5)).Toolbar(new List<string> { "PdfExport", "Print", "ExcelExport", "ColumnChooser", "Search" }).Render()
                    </div>*@
                    <div class="col-12">
                  
                        @{
                            var gridmodel=new GridModel()
                            {
                GridId = "list",
                Columns=new List<Column>
                {
                        new Column{FieldName="className",HeaderText="Class",TextAlign=TextAlign.Left},
                        new Column{FieldName="feeGroupName",HeaderText="Fee Group",Width="100",TextAlign=TextAlign.Left},
                        new Column{FieldName="amount",HeaderText="Amount",Width="100",TextAlign=TextAlign.Left},
                        new Column{FieldName="action",Template="#action",HeaderText="Action",Width="70",TextAlign=TextAlign.Left},
                },
                            };
                        }
                        @await Html.PartialAsync("_grid",gridmodel)
                    </div>
                    <script type="text/x-jsrender" id="action">
                        <a title="Delete" href="/Fee/ClassfeeDelete/${id}" class="delete ml-1"><i class="fa fa-trash"></i></a>
                        <a title="Fee Structure" href="/Fee/FeestructIndex?feegroupid=${feeGroupID}&campId=${campusID}" class="ajax-load ml-1"><i class="fa fa-edit"></i></a>
                    </script>
                </div><!-- /.box-body -->
            </div>
        </div><!--/.col (left) -->
        <!-- right column -->
    </div>
</section>

<script @resources.JavaScript>

    function reloadGridData() {
        
        var grid = document.getElementById("list").ej2_instances[0];
        grid.dataSource = [];
        var campusId = $('#Campus').val();
        if ( !campusId)
            return false;

       var url = '@Url.Action("ClassFeeGroupList")';
                url += '?campusId=' + campusId;

        grid.dataSource = new ej.data.DataManager({
            url: url,
            adaptor: new ejs.data.UrlAdaptor()
        });
    }
    $('#list').on('click', 'a.ajax-load', function (e) {
        e.stopPropagation();
        var url = window.$(this).attr('href');
        Navigate(url);
        return false;
    })
    $('#list').on('click',
        'a.delete',
        function (e) {
            e.preventDefault();
            var title = 'Class Fee Group';
            var url = $(this).attr('href');

            BootstrapDialog.show({
                title: title,
                message: $('#bootstrap-diallog').html('<div />').load(url),
                onhide: function (dialogRef) {
                    $('body').append('<div id="bootstrap-diallog"></div>');
                    reloadGridData();
                }
            });
            return false;
        });
  
        $('#Classes').on('change',
            function() {
                var clas = $('#Classes').val();
                let campusid = $('#Campus').val();
                if (!clas || !campusid)
                    return false;
                $.get('/api/fee/getfeeGroup/' + clas + "?campusId=" + campusid,
                    function(data, status) {
                        if (data != null) {
                            $('#FeeGroupID').val(data);
                            $('#FeeGroupID').trigger('change');
                        }
                    });
            });

    $('#Campus').on('change',
        function () {
            reloadGridData();
        });
</script>

smsCore/Views/Fee/DiscountorFine.cshtml
@inject StaticResources resources

@{
    ViewBag.Title = "Discount or Fine";
}

<div class="breadcrumbs ace-save-state" id="breadcrumb">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home ace-icon home-icon">

            </i>
            <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
        </li>
        <li class="active">
            Discount or Fine
        </li>

    </ul>
</div>

@*<div class="col-md-12 mainDive">
    <div class="card mb-4">*@

<section class="content" id="searchstudent-container">
    <div class="row">

        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title"><i class="fa fa-search"></i> Select Criteria <a href="https://www.youtube.com/watch?v=tWKtJDvxtT8&list=UUQFf95Tyl3o9y-DE0vvlTQg#t=115s" target="_blank" class="btn btn-default btn-sm float-right"><i class="fa fa-question-circle"></i> Help </a></h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                @*<div class="col-md-3 col-12">
                                <label> For Month:</label><font class="text-danger">*</font>
                                <div class="controls date-picker-container">
                                <input type="text" class="input-month-picker form-control" readonly />
                                <input type="hidden" name="month" class="date form-control" id="month" />
                                <span class="fa fa-calendar form-control-feedback left" aria-hidden="true"></span>
                                </div>
                                </div>*@
                                @await Html.PartialAsync("_PartialDate", new PartialDateViewModels { Label = "Month:", PickerType = "month", Format = "MM yy", ParentContainerID = "mont-date", ColCssClass = "col-md-3 col-12", ShowAltField = true, AltFieldId = "month", AltFieldName = "month", AltFieldFormat = "dd/mm/yy", DateFieldId = "monthpick", DateFieldName = "monthpick", KeepDataFieldReadOnly = true })

                                @await Html.PartialAsync("_PartialCampusSelector", new PartialCampusViewModels { ParentContainerID = "searchstudent-container", ColCssClass = "col-6 col-sm-3 col-md-3", ShowCampus = true, ShowClasses = true})
                                <div class="col-12"></div>
                                <div class="col-md-3 col-12">
                                    <label>
                                        Fee Type
                                    </label>
                                    <div class="controls">
                                        <select name="feetype" id="feetype" class="form-control"></select>
                                        <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                                    </div>
                                </div>
                                <div class="col-md-3 col-12">
                                    <label>
                                        Amount
                                    </label>
                                    <div class="controls">
                                        <input type="text" name="amounts" class="form-control" id="amounts" value="0" />
                                        <span class="form-control-feedback left" aria-hidden="true">
                                            <i class="fa fa-dollar-sign"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-sm-12 mt-3">

                                    <button type="button" name="search" onclick="$('#search_text').val('');searches(this);" value="search_filter" class="btn btn-primary btn-sm pull-right checkbox-toggle"><i class="fa fa-search"></i> Search</button>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header with-border">
            <h3 class="card-title"><i class="fa fa-list"></i> Student List</h3>
        </div>
        <div class="card-body">
            <p class="col-12" id="message"></p>
            <div class="col-12">
                @*@Html.EJS().Grid("list").AllowSelection().Columns(col =>
                {
                col.Type("checkbox").Width("50").AllowEditing(true).Add();
                col.Field("RegistrationNo").HeaderText("Reg. No").Width("100").TextAlign(TextAlign.Left).AllowEditing(false).Add();
                col.Field("StudentName").HeaderText("Name").TextAlign(TextAlign.Left).AllowEditing(false).Add();
                col.Field("FName").HeaderText("Father's Name").TextAlign(TextAlign.Left).AllowEditing(false).Add();
                col.Field("ClassName").HeaderText("Class").Width("100").AllowEditing(false).TextAlign(TextAlign.Left).Add();
                col.Field("Amount").HeaderText("Amount").AllowEditing(true).Width("100").Add();
                }).Load("load").AllowFiltering().AllowPaging().EditSettings(edit => { edit.AllowEditing(true).Mode(Syncfusion.EJ2.Grids.EditMode.Batch); }).SelectionSettings(select => select.CheckboxOnly(true).CheckboxMode(Syncfusion.EJ2.Grids.CheckboxSelectionType.Default).Type(Syncfusion.EJ2.Grids.SelectionType.Multiple)).FilterSettings(filter => filter.Type(FilterType.Menu)).Height("auto").Width("auto").AllowExcelExport().AllowPdfExport().ShowColumnMenu().ShowColumnChooser().AllowResizing().PageSettings(page => page.PageSize(15)).Toolbar(new List<string> { "PdfExport", "Print", "ExcelExport", "ColumnChooser", "Search" }).Render()*@
                @{
                    var girdModel = new GridModel()
            {
                GridId = "list",
                Columns = new List<Column>
                {
                new Column{Type="checkbox",Width="50",AllowEditing=true},
                new Column{FieldName="registrationNo",HeaderText="Reg. No",Width="100",TextAlign=TextAlign.Left,AllowEditing=false},
                new Column{FieldName="studentName",HeaderText="Name",TextAlign=TextAlign.Left,AllowEditing=false},
                new Column{FieldName="fName",HeaderText="Father's Name",Width="",TextAlign=TextAlign.Left,AllowEditing=false},
                new Column{FieldName="className",HeaderText="Class",Width="100",TextAlign=TextAlign.Left,AllowEditing=false},
                new Column{FieldName="amount",HeaderText="Amount",Width="100",TextAlign=TextAlign.Left,AllowEditing=true},
                },
            };
                }
                @await Html.PartialAsync("_grid",girdModel)
                </ div >

                </ div >

                <div class=" card-footer">
                    <button type="button" class="btn float-right btn-primary" id="btnSave"><i class="fa fa-save"></i> Save</button>
                </div>
            </div>

        </div>
    </div>
</section>

<script @resources.JavaScript>
    function load(args) {
        var instance = document.getElementById('list').ej2_instances[0];
        instance.element.addEventListener('mousedown', function (e) {
            if (e.target.classList.contains("e-rowcell")) {
                var index = parseInt(e.target.getAttribute("Index"));
                var colindex = parseInt(e.target.getAttribute("aria-colindex"));
                var field = instance.getColumns()[colindex].field;
                instance.editModule.editCell(index, field);
            };
        });
    }
    function reloadGridData() {

        var classid = $('#Classes').val();
        var typeId = $('#feetype').val();
        var month = $('#month').val();

        var amounts = $('#amounts').val();
        if ($('#month').val() == null || $('#month').val() == "") {
            $('#month').focus();
            return
        }
        var grid = document.getElementById("list").ej2_instances[0];
        grid.dataSource = [];
        var url = '@Url.Action("FeedetailsForDiscountOrFine")';
        url += '?campusId=' + $('#Campus').val() + '&classid=' + classid + '&typeId=' + typeId + '&formonth=' + month + '&amounts=' + amounts;


        grid.dataSource = new ej.data.DataManager({
            url: url,
            adaptor: new ejs.data.UrlAdaptor()
        });
    }

    var fee_url = '/api/fee/GetFeetype';
    $.get(fee_url,
        function (data) {
            var newdata = JSON.parse(data);
            $('#feetype').html('').select2({
                data: newdata,
                width: '100%'
            });
        });

    $('#Classes').on('change', function () { $('#feetype').trigger('change'); });
    $('#feetype').on('change',
        function () {
            if ($('#month').val() == null || $('#month').val() == "") {
                $('#month').focus();
                return
            }
            var url = '/api/fee/GetFeetypeAmount';
            url += '?typeId=' + $(feetype).val() + '&campus=' + $('#Campus').val() + '&classes=' + $('#Classes').val();
            $.get(url,
                function (data) {
                    $('#amounts').val(data);
                });
        });


    $('#btnSave').on('click',
        function () {

            var feetype = $('#feetype').val();
            var result = [];
            var data = [];
            var grid = document.getElementById("list").ej2_instances[0];
            console.log(grid);
            var changedrecords = grid.getBatchChanges().changedRecords;  // getCurrentEditCellData get the selected records.
            let allselectedrecords = grid.getSelectedRecords();

            var i = 0;
            let selectedrecords = allselectedrecords.map(function (v) {
                let changed = changedrecords.find(function (f) {
                    return v.Id == f.Id;
                });
                if (changed) {
                    v.Amount = changed.Amount;
                }
                return v;
            });
            if (selectedrecords.length == 0) {

                sweetalert("Plaese select atleast one student before continue", '', 'error');
                return false;
            }
            $.each(selectedrecords, function (i, v) {
                data[i] = v.Amount;
                result[i] = v.Id;
            });
            
            $.post('@Url.Action("fineordiscountsave", "Fee")',
                { Id: result, amount: data, feetype: feetype },
                function (result) {

                    if (result == "success") {

                        $('#message').html('<p class="alert alert-info w-100">Information Updated to database successfully.<a class="close" style="top: 4px;position: absolute;right: 7px;" onclick="clearMessage();"><i class="fa fa-close"></i></a></p>');
                        reloadGridData();
                    }
                    else {
                        $('#message').html('<p class="alert alert-danger w-100">' + result + '<a class="close" style="top: 4px;position: absolute;right: 7px;" onclick="clearMessage();"><i class="fa fa-close"></i></a></p>');
                    }
                });

        });
    $('#amounts').on('change',
        function () {
            $('.amountId').val($(this).val());
        });

    function searches() {
        reloadGridData();
    }

</script>

smsCore/Views/Fee/FeeSlipReceiptDelete.cshtml
@model  FeeSlipReceipt
@{
    ViewBag.Title = "Fee Slip Receipt Delete";
    //if (Request.IsAjaxRequest())
    //{
    //    Layout = null;
    //}
}

@*@using (Ajax.BeginForm("FeeSlipReceiptDelete", "Fee", new AjaxOptions { HttpMethod = "POST", OnSuccess = "reloadGridData", OnComplete = "completed", LoadingElementId = "FeeSlipReceiptDeletemainForm #server-progress", OnBegin = "begin" }, new { id = "FeeSlipReceiptDeletemainForm" }))
{*@
<form asp-action="FeeSlipReceiptDelete" asp-controller="Fee"
      data-ajax="true" data-ajax-method="post" enctype="multipart/form-data" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="FeeSlipReceiptDeletemainForm" data_reset="true">
                   



    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-12">
            <div>
                <h5>Are You Sure You Want to delte it.</h5>
            </div>
            <div id="message">

            </div>
        </div>
    </div>
    <div class="form-group col-12 mt-2 pb-2">
        <a href="@Url.Action("EditFeeIndex", "Fee")" aria-label="Back to Dashboard" class="btn btn-danger"> <i class="fa fa-chevron-circle-left mr-2"></i> Back to Fee Slip</a>
        <button type="submit" value="Create" class="btn btn-danger pull-right">
            <i class="fa fa-trash mr-2"></i> <span>
                <i id="server-progress" style="display:none;" class=" fa fa-spinner fa-spin "></i>
            </span> Delete
        </button>
    </div>
</form>