smsCore/Controllers/HostelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models;
using Newtonsoft.Json;
using smsCore.Data;
using smsCore.Data.Helpers;
using Syncfusion.EJ2.Base;

namespace smsCore.Controllers
{
    [Authorize]
    public class HostelController : BaseController
    {
        // GET: Hostel
        private readonly SchoolEntities db;
        private readonly CurrentUser _user;

        public HostelController(SchoolEntities _db, CurrentUser user)
        {
            db = _db;
            _user = user;
        }

        #region Hostel

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public string Create(Hostel hostel)
        {
            try
            {
                hostel.CampusId = _user.SelectedCampusId;
                db.Hostels.Add(hostel);
                db.SaveChanges();
                return "success";
            }
            catch (Exception ex)
            {
                ModelState.Clear();
                return ex.Message;
                //return RedirectToAction("Create");
            }
        }


        public IActionResult Edit(int id)
        {
            //HostelEntities db = new HostelEntities();
            var getdata = db.Hostels.Where(w => w.Id == id).FirstOrDefault();
            return View(getdata);
        }


        [HttpPost]
        public string Edit(Hostel hostel)
        {
            var hostelToUpdate = db.Hostels.Find(hostel.Id);
            if (hostelToUpdate != null)
            {
                hostelToUpdate.HostelName = hostel.HostelName;
                hostelToUpdate.TotalRooms = hostel.TotalRooms;
                hostelToUpdate.TotalStudents = hostel.TotalStudents;
                hostelToUpdate.Location = hostel.Location;
                hostelToUpdate.CampusId = hostel.CampusId;
            }
            else
            {
                return "failed";
            }

            try
            {
                db.SaveChanges();

                return "success";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            var getdata = db.Hostels.Where(w => w.Id == id).FirstOrDefault();
            return View(getdata);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public string Delete(Hostel hostel)
        {
            var message = string.Empty;
            try
            {
                hostel = db.Hostels.Find(hostel.Id);
                db.Hostels.Remove(hostel);
                db.SaveChanges();
                message = "delete";
            }
            catch (Exception aa)
            {
                message = aa.Message;
                //ModelState.AddModelError("", aa.Message);
            }

            return message;
        }


        [HttpPost]
        public ActionResult GethostelList(DataManagerRequest dm)
        {

            var hostellist = db.Hostels.Select(s => new
            {
                s.Id,
                s.HostelName,
                s.Location,
                s.TotalRooms,
                s.TotalStudents,
                s.Campus.CampusName,
            });
            DataOperations operation = new DataOperations();
            if (dm.Search != null && dm.Search.Count > 0)
            {
                hostellist = operation.PerformSearching(hostellist, dm.Search);  //Search
            }
            if (dm.Sorted != null && dm.Sorted.Count > 0) //Sorting
            {
                hostellist = operation.PerformSorting(hostellist, dm.Sorted);
            }
            if (dm.Where != null && dm.Where.Count > 0) //Filtering
            {
                hostellist = operation.PerformFiltering(hostellist, dm.Where, dm.Where[0].Operator);
            }
            int count = hostellist.Count();
            if (dm.Skip != 0)
            {
                hostellist = operation.PerformSkip(hostellist, dm.Skip);   //Paging
            }
            if (dm.Take != 0)
            {
                hostellist = operation.PerformTake(hostellist, dm.Take);
            }
            if (dm.RequiresCounts)
            {
                return Json(new { result = hostellist, count = hostellist.Count() });
            }
            else
            {
                return Json(new { result = hostellist, count = hostellist.Count() });
            }
        }

        #endregion
        #region Hostel Room

        public IActionResult HostelRoom()
        {
            ViewBag.hstlename = new SelectList(db.Hostels, "Id", "HostelName");
            return View();
        }

        [HttpPost]
        public string HostelRoom(Room room)
        {
            try
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                return "success";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        public IActionResult GetRoomList(DataManagerRequest dm)
        {
            var roomList = db.Rooms.Select(d => new
            {
                d.Id,
                d.Hostel.HostelName,
                d.RoomNo,
                d.Floor,
                d.Capacity
            });
            DataOperations operation = new DataOperations();
            if (dm.Search != null && dm.Search.Count > 0)
            {
                roomList = operation.PerformSearching(roomList, dm.Search);  //Search
            }
            if (dm.Sorted != null && dm.Sorted.Count > 0) //Sorting
            {
                roomList = operation.PerformSorting(roomList, dm.Sorted);
            }
            if (dm.Where != null && dm.Where.Count > 0) //Filtering
            {
                roomList = operation.PerformFiltering(roomList, dm.Where, dm.Where[0].Operator);
            }
            int count = roomList.Count();
            if (dm.Skip != 0)
            {
                roomList = operation.PerformSkip(roomList, dm.Skip);   //Paging
            }
            if (dm.Take != 0)
            {
                roomList = operation.PerformTake(roomList, dm.Take);
            }
            if (dm.RequiresCounts)
            {
                return Json(new { result = roomList, count = roomList.Count() });
            }
            else
            {
                return Json(new { result = roomList, count = roomList.Count() });
            }
        }


        public IActionResult EditRooms(int id)
        {
            var getdata = db.Rooms.Where(w => w.Id == id).FirstOrDefault();
            ViewBag.hstlename = new SelectList(db.Hostels, "Id", "HostelName", getdata.HostelId);
            return View(getdata);
        }
        [HttpPost]
        public string EditRooms(Room room)
        {
            var roomToUpdate = db.Rooms.Find(room.Id);
            if (roomToUpdate != null)
            {
                roomToUpdate.RoomNo = room.RoomNo;
                roomToUpdate.Floor = room.Floor;
                roomToUpdate.Capacity = room.Capacity;
                roomToUpdate.HostelId = room.HostelId;
            }
            else
            {
                return "failed";
            }

            try
            {
                db.SaveChanges();
                return "success";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }


        public IActionResult DeleteRooms(int id)
        {
            var getdata = db.Rooms.Where(w => w.Id == id).FirstOrDefault();
            return View(getdata);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public string DeleteRooms(Room room)
        {
            var message = string.Empty;
            try
            {
                room = db.Rooms.Find(room.Id);
                db.Rooms.Remove(room);
                db.SaveChanges();
                message = "delete";
            }
            catch (Exception aa)
            {
                message = aa.Message;
                //ModelState.AddModelError("", aa.Message);
            }

            return message;
        }

        #endregion

        #region Hostel Admission
        public IActionResult HostelAdmission()
        {
            var campusId = _user.GetCampusIds();
            ViewBag.hostelname = new SelectList(db.Hostels.Select(s => new { s.Id, s.HostelName }), "Id", "HostelName");
            ViewBag.roomno = new SelectList(db.Rooms, "Id", "RoomNo");
            return View();
        }


        [HttpPost]
        public string HostelAdmissionCreate(HostelAdmission hadmission)
        {
            if (!int.TryParse(Request.Form["regNo"], out var regno)) return "Invalid reg No";
            var admissionid = db.Admissions.Where(w => w.Student.RegistrationNo == regno && !w.IsExpell)
                .Select(s => s.ID).FirstOrDefault();
            if (admissionid <= 0) return "regNo is Invalid";
            var hosteladmission = db.HostelAdmissions.Where(w => !w.Isexpel && w.AdmisionId == admissionid).ToList();
            if (hosteladmission.Count() > 0) return "Registration Number is Already Exist";
            try
            {
                var hostelAdm = new HostelAdmission()
                {
                    AdmisionId = admissionid,
                    AdmissionDate = DateTimeHelper.ConvertDate(Request.Form["AdmissionDate"].ToString(), true),
                    Fee = hadmission.Fee,
                    HostelId = hadmission.HostelId,
                    Isexpel = false,
                    RoomId = hadmission.RoomId
                };
                db.HostelAdmissions.Add(hostelAdm);
                db.SaveChanges();
                return "success";
            }
            catch (Exception ex)
            {

smsCore/Views/Hostel/DeleteRooms.cshtml
@model Room
@inject StaticResources resources

@{
    ViewBag.Title = "Delete";
    //if (Request.IsAjaxRequest())
    //{
    //    Layout = null;
    //}
}

<h5>Are you sure you want to delete?</h5>

<div>

    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hostel.HostelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hostel.HostelName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RoomNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomNo)
        </dd>
        <dt>
        @Html.DisplayNameFor(model => model.Capacity)

        <dd>
            @Html.DisplayFor(model => model.Capacity)

        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Floor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Floor)
        </dd>


    </dl>
   @* @using (Ajax.BeginForm("DeleteRooms", "Hostel", new AjaxOptions {HttpMethod = "POST", OnSuccess = "disablebutton", OnComplete = "completed", LoadingElementId = "DeletemainForm #server-progress", OnBegin = "begin"}, new {id = "DeletemainForm"}))
    {*@
    <form asp-action="DeleteRooms" asp-controller="Hostel"
          data-ajax="true" data-ajax-method="post" enctype="multipart/form-data" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="DeletemainForm" data_reset="true">
                   


        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-12">
                <div id="message">

                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id"/>
        <button asp="Index" data-dismiss="modal" aria-label="Close" class="btn btn-danger float-right btn-sm "> <i class="fa fa-chevron-circle-left mr-2"></i> Cancel and Close</button>
        <button type="submit" value="Create" id="submitbuttom" class="btn btn-primary float-right btn-sm">
            <i class="fa fa-save mr-2"></i>
            <span>
                <i id="server-progress" style="display: none;" class=" fa fa-spinner fa-spin "></i>

            </span> Delete
        </button>
    </form>
</div>
<script @resources.JavaScript>
    function disablebutton() {
        $('#submitbuttom').hide();
    }
</script>

smsCore/Views/Hostel/Edit.cshtml
@using sms.Models
@model  Hostel

@{
    ViewBag.Title = "Edit";
    //if (Request.IsAjaxRequest())
    //{
    //    Layout = null;
    //}
}

@*@using (Ajax.BeginForm("Edit", "Hostel", new AjaxOptions {HttpMethod = "POST", OnComplete = "completed", OnSuccess = "reloadGridData", LoadingElementId = "editHostelmainForm #server-progress", OnBegin = "begin"}, new {id = "editHostelmainForm", enctype = "multipart/form-data"}))
{*@
<form asp-action="Edit" asp-controller="Hostel"
      data-ajax="true" data-ajax-method="post" enctype="multipart/form-data" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="editHostelmainForm" data_reset="true">
                   


    <div class="row">
        <div class="col-12">
            <div id="message">

            </div>
        </div>
    </div>
    <div class="Container" id="hosteledit">

        <div class="row ">


            @Html.Partial("_PartialCampusSelector", new PartialCampusViewModels {ParentContainerID = "hosteledit", ColCssClass = "col-12 col-sm-6 has-feedback", CampusID = Model.CampusId, CampusFieldName = "CampusId", ShowCampus = true})

            <div class="col-12 col-sm-6 has-feedback">
                <div  class="controls">
                    <label>Hostel Name</label><font class="text-danger">*</font>
                    @Html.TextBoxFor(model => model.HostelName, new { @class = "small form-control has-feedback-left", required = "true" })
                    <span class="fa fa-building small form-control-feedback left" aria-hidden="true"></span>
                    @Html.ValidationMessageFor(model => model.HostelName)
                </div>
            </div>
            <div class="col-12 col-sm-6 has-feedback">
                <label>Total Students</label><font class="text-danger">*</font>
                                             <div  class="controls">
                                                 @Html.TextBoxFor(model => model.TotalStudents, new { @class = "small form-control has-feedback-left", required = "true", type = "number" })
                                                 <span class="fa fa-users small form-control-feedback left" aria-hidden="true"></span>
                                                 @Html.ValidationMessageFor(model => model.TotalStudents)
                                             </div>

            </div>
            <div class="col-12 col-sm-6 has-feedback">
                <label>Total Rooms</label><font class="text-danger">*</font>
                                          <div  class="controls">
                                              @Html.TextBoxFor(model => model.TotalRooms, new { @class = "small form-control has-feedback-left", required = "true", type = "number" })
                                                          <span class="fa fa-bed small form-control-feedback left" aria-hidden="true"></span>
                                                          @Html.ValidationMessageFor(model => model.TotalRooms)
                                                      </div>
            </div>
            @*<div class="col-12 col-md-4 col-sm-6 has-feedback">
            <label>AnnualExpense</label>
            @Html.TextBoxFor(model => model.AnnualExpense, new { @class = "small form-control has-feedback-left", required = "true" })
            <span class="fa fa-money small form-control-feedback left" aria-hidden="true"></span>
            @Html.ValidationMessageFor(model => model.AnnualExpense)
        </div>*@
            <div class="col-12 col-sm-6 has-feedback">
                <label>Location</label><font class="text-danger">*</font>
                                       <div  class="controls">
                                           @Html.TextBoxFor(model => model.Location, new { @class = "small form-control has-feedback-left", required = "true" })
                                           <span class="fa fa-map-marker small form-control-feedback left" aria-hidden="true"></span>
                                           @Html.ValidationMessageFor(model => model.Location)
                                       </div>
            </div>

        </div>

        <div class="row">
            <div class="col-12">
               @* <a href="@Url.Action("Index", "Hostel")" aria-label="Close" class="btn btn-danger float-left mt-2"> <i class="fa fa-times mr-2"></i>Back to Dashboard</a>*@
                <button type="reset" name="Reset" id="resetbtn" class="btn btn-primary float-right mt-2 btn-sm"><i class="fa fa-refresh mr-2"></i>Reset</button>
                <button type="submit" value="Edit" name="Update" id="updatebtn" class="btn btn-primary float-right mt-2 mr-2 btn-sm">
                    <i class="fa fa-save mr-2"></i>
                    <span>
                        <i id="server-progress" style="display: none;" class=" fa fa-spinner fa-spin "></i>
                    </span> Save
                </button>
            </div>
        </div>
    </div>
</form>

smsCore/Views/Hostel/HostelAdmission.cshtml
@model HostelAdmission
@inject StaticResources resources

@{
    ViewBag.Title = "Index";
    //if (Request.IsAjaxRequest())
    //{
    //    Layout = null;
    //}
}

<div class="breadcrumbs ace-save-state" id="breadcrumb">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home ace-icon home-icon">

            </i>
            <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
        </li>
        <li class="active">
            Hostel Admission
        </li>
    </ul>
</div>
<section class="content">
    @* @using (Ajax.BeginForm("HostelAdmissionCreate", "Hostel", new AjaxOptions { HttpMethod = "POST", OnComplete = "completed", OnSuccess = "reloadGridData", LoadingElementId = "edithosteladmissionmainForm #server-progress", OnBegin = "begin" }, new { id = "editvisitormainForm", enctype = "multipart/form-data", data_reset = "true" }))
    {*@

    <form asp-action="HostelAdmissionCreate" asp-controller="Hostel" data-ajax="true" data-ajax-method="post" enctype="multipart/form-data" data-ajax-complete="completed" data-ajax-begin="begin" class="form-horizontal form-label-left input_mask" id="editvisitormainForm" data_reset="true">

        <div class="row">
            <div class="col-12 ">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title titlefix">Hostel Admission Record <a href="https://www.youtube.com/watch?v=yqoeHNNcBCw&list=UUQFf95Tyl3o9y-DE0vvlTQg#t=100s" target="_blank" class="btn btn-default btn-sm float-right"><i class="fa fa-question-circle"></i> Help </a></h3>
                    </div>
                    <div class="card-body">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)

                        <div class="row">
                            <div class="col-12">
                                <div id="message">
                                </div>
                            </div>
                        </div>
                        <div class="row ">

                            @* @Html.Partial("_PartialCampusSelector", new PartialCampusViewModels { ParentContainerID = "room", ColCssClass = "col-12 col-md-3 col-sm-4 has-feedback", CampusFieldName = "CampusId", ShowCampus = true })*@
                            <div class="col-12 col-md-3 col-sm-4 has-feedback">
                                <label>Hostel</label><font class="text-danger">*</font>
                                <div class="controls">
                                    @Html.DropDownListFor(model => model.HostelId, (SelectList)ViewBag.hostelname, new { @class = " form-control has-feedback-left", required = "true" })
                                    <span class="fa fa-building small form-control-feedback left" aria-hidden="true"></span>
                                    @Html.ValidationMessageFor(model => model.HostelId)
                                </div>
                            </div>

                            <div class="col-12 col-md-3 col-sm-4 has-feedback">
                                <label>Room</label>
                                <div class="controls">
                                    <select name="RoomId" id="roomId" class="form-control"></select>
                                    @Html.DropDownListFor(model => model.RoomId, (SelectList)ViewBag.roomno, new { @class = "form-control has-feedback-left", id="roomId", required = "true"})
                                    @*<input type="text" id="roomavailable" readonly class="col-6" style="background-color: #D5D5D5; color: black; height: 28px;" />*@

                                    <label style="background-color: #FFBC53; color: black; margin-top: 0px; padding: 4px; text-align: center; width: 118px;">Seat available</label>

                                    <span class="fa fa-home small form-control-feedback left" aria-hidden="true"></span>
                                    @Html.ValidationMessageFor(model => model.RoomId)
                                </div>
                            </div>

                            <div class="col-12 col-md-3 col-sm-4 has-feedback">
                                <label> Reg No</label><font class="text-danger">*</font>
                                <div class="controls">
                                    <input type="number" name="regNo" class=" form-control" required />
                                    <span class="fa fa-registered form-control-feedback left" aria-hidden="true"></span>
                                    @Html.ValidationMessageFor(model => model.AdmisionId)
                                </div>
                            </div>

                            @await Html.PartialAsync("_PartialDate", new PartialDateViewModels
                            {
                            Label = "Admission Date",
                            ParentContainerID = "adm-date",
                            ColCssClass = "col-12 col-md-3 col-sm-4 date",
                            ShowAltField = false,
                            DateFieldId = "AdmissionDate",
                            DateFieldName = "AdmissionDate",
                            KeepDataFieldReadOnly = true,
                            DefaultDate = DateTime.Now
                            })
                            <div class="col-12 col-md-3 col-sm-4 has-feedback" style="margin-top: -27px">
                                <label>Fee</label>
                                <div class="controls">
                                    @Html.TextBoxFor(model => model.Fee, new { @class = " form-control has-feedback-left" })
                                    <span class="fa fa-dollar-sign form-control-feedback left" aria-hidden="true"></span>
                                    @Html.ValidationMessageFor(model => model.Fee)
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-12">
                                @* <a href="@Url.Action("Index", "HostelAdmission")" aria-label="Close" class="btn btn-danger float-left mt-2"> <i class="fa fa-arrow mr-2"></i>Back to Dashboard</a>*@
                                <button type="reset" name="Reset" id="resetbtn" class="btn btn-primary float-right mt-2"><i class="fa fa-refresh mr-2"></i>Reset</button>
                                <button type="submit" value="Create" name="Update" id="updatebtn" class="btn btn-primary float-right mt-2 mr-2">
                                    <i class="fa fa-save mr-2"></i>
                                    <span>
                                        <i id="server-progress" style="display: none;" class=" fa fa-spinner fa-spin "></i>
                                    </span> Save
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title titlefix">Hostel Admission List</h3>
                </div>
                <div class="card-body">
                    @* @Html.EJS().Grid("GridS").AllowFiltering().FilterSettings(filter => filter.Type(FilterType.Menu)).AllowGrouping().Height("300").Width("auto").AllowExcelExport().AllowPdfExport().ShowColumnMenu().ShowColumnChooser().AllowResizing().Columns(col =>
                    {
                    col.Field("RegNo").HeaderText("Reg No").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Left).Add();
                    col.Field("StudentName").HeaderText("Students").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Left).Add();
                    col.Field("RoomNo").HeaderText("Room No").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Left).Add();
                    col.Field("AdmissionDate").HeaderText("Admission Date").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Left).Add();
                    col.Field("Fee").HeaderText("Fee").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Left).Add();
                    col.Field("action").Template("#action").HeaderText("Action").Width("70").TextAlign(TextAlign.Center).Add();

                    }).FilterSettings(filter => { filter.Type(Syncfusion.EJ2.Grids.FilterType.CheckBox); }).AllowSorting(true).PageSettings(page => page.PageSize(5)).Toolbar(new List<string>()
                    { "PdfExport", "Print", "ExcelExport", "Search" ,"ColumnChooser" }).Render()*@
                    @{
                        var modelgrid = new GridModel()
            {
                GridId = "GridS",
                AllowExcelExport = true,
                AllowPdfExport = true,
                AllowGrouping = true,
                Width = "auto",
                Height = "auto",
                ShowHeader = false,
                Columns = new List<Column>
                    {
                    new Column{FieldName="regNo",HeaderText="Reg No",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="studentName",HeaderText="Students",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="roomNo",HeaderText="Room No",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="admissionDate",HeaderText="Admission Date",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="fee",HeaderText="Fee",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},
                    new Column{FieldName="action",HeaderText="Action",Template="#action",AllowSorting=true,Width="auto",HeaderTextAlign=TextAlign.Left},

                    },
                AllowFiltering = true,
            };
                    }
                    @await Html.PartialAsync("_grid",modelgrid)

                    <script type="text/x-jsrender" id="action">
                        <a title="Edit" class="editL" id="${Id}" href="/Hostel/HostelAdmissionEdit/${Id}"><i class="fa fa-edit"></i></a>
                        <a title="Delete" class="delete" id="${Id}" href="/Hostel/HostelAdmissionDelete/${Id}"><i class="fa fa-trash ml-2"></i></a>
                    </script>
                </div>
            </div>
        </div>
    </form>
</section>
@Html.EJS().ScriptManager()

<script @resources.JavaScript>
    $('#updatebtn').disable();
    setTimeout(function () {
        $('#HostelId').trigger('change');
        $('#roomId').trigger('change');
    },
        300);

    $('#HostelId').on('change',
        function () {
            var url = '@Url.Action("Getroom", "Hostel")';
            url += '?hostelId=' + $('#HostelId').val();
            $.get(url,
                function (data) {
                    var data = JSON.parse(data);

                    $('#roomId').html('').select2({
                        data: data,
                        width: '100%'
                    });
                    $('#roomId').trigger('change');
                });
        });
    setTimeout(function () {
    },
        700);
    $('#roomId').on('change',
        function () {
            $('#updatebtn').disable();
            var url = '@Url.Action("Getavalaibleroom", "Hostel")';
            url += '?roomId=' + $('#roomId').val();
            $.get(url,
                function (data) {
                    var data = JSON.parse(data);

                    $('#roomavailable').val(data.roomavailable);
                    if (parseInt(data.roomavailable) > 0) {
                        $('#updatebtn').enable();
                    } else {
                        $('#updatebtn').disable();
                    }
                    $('#roomavailable').trigger('change');
                });

        });
    $(document).ready(function () {
        var url2 = '@Url.Action("GetHostelAdmissionList")';
        var grid = document.getElementById("GridS").ej2_instances[0];
        grid.dataSource = [];
        grid.dataSource = new ej.data.DataManager({
            url: url2,
            adaptor: new ejs.data.UrlAdaptor()
        });
    });

    function reloadGridData() {
        var gird = document.getElementById('GridS').ej2_instances[0];
        gird.refresh();
    }
    // Modal For Delete Staff Issued Book List //
    $('#GridS').on('click',
        'a.delete',
        function (e) {
            e.preventDefault();
            var title = "Delete Admissions"
            var url = $(this).attr('href');

            BootstrapDialog.show({
                title: title,
                message: $('#bootstrap-diallog').html('<div />').load(url),
                onhide: function (dialogRef) {
                    $('body').append('<div id="bootstrap-diallog"></div>');
                    reloadGridData();
                }
            });
            return false;
        });

    $('#GridS').on('click',
        'a.editL',
        function (e) {
            e.preventDefault();
            var url = $(this).attr('href');
            var title = "Edit Hostel Admission"

            BootstrapDialog.show({
                title: title,
                message: $('#bootstrap-diallog').html('<div />').load(url),
                onhide: function (dialogRef) {
                    $('body').append('<div id="bootstrap-diallog"></div>');
                    reloadGridData();
                }
            });
            return false;
        });

</script>